language: python

python:
 - pypy
 - pypy3
 - 2.6
 - 2.7
 - 3.2
 - 3.3
 - 3.4
 - 3.5

# Use container-based infrastructure
sudo: false

install:
 - pip install nose
 # Coverage 4.0 doesn't support Python 3.2
 - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then pip install "coverage<4"; fi
 - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then pip install coverage; fi

script:
 - coverage run --source olefile Tests/test_olefileio.py

after_success:
 - coverage report
 - pip install coveralls
 - coveralls
 - pip install pep8 pyflakes
 - pyflakes .
 - pep8 --statistics --count .

matrix:
  fast_finish: true
